
[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "docs_codegen"
repository.workspace = true
version              = "0.0.0"

[dependencies]
regex              = { workspace = true }
anyhow                     = { workspace = true }
bpaf                     = { workspace = true, features = ["docgen"] }
schemars       = { workspace = true }
serde       = { workspace = true }
serde_json       = { workspace = true }
pulldown-cmark          = "0.12.2"

pglt_configuration = { workspace = true, features = ["schema"] }
pglt_flags = { workspace = true }
pgt_cli = { workspace = true }
pglt_analyse = { workspace = true }
pglt_analyser = { workspace = true }
pglt_diagnostics = { workspace = true }
pglt_query_ext = { workspace = true }
pglt_workspace = { workspace = true }
pglt_statement_splitter = { workspace = true }
pglt_console = { workspace = true }
biome_string_case = { workspace = true }

