[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pgt_lsp"
repository.workspace = true
version              = "0.0.0"


[dependencies]
anyhow                  = { workspace = true }
biome_deserialize       = { workspace = true }
futures                 = "0.3.31"
pgt_analyse             = { workspace = true }
pgt_completions         = { workspace = true }
pgt_configuration       = { workspace = true }
pgt_console             = { workspace = true }
pgt_diagnostics         = { workspace = true }
pgt_fs                  = { workspace = true }
pgt_lsp_converters      = { workspace = true }
pgt_text_edit           = { workspace = true }
pgt_text_size.workspace = true
pgt_workspace           = { workspace = true, features = ["db-connection"] }
rustc-hash              = { workspace = true }
serde                   = { workspace = true, features = ["derive"] }
serde_json              = { workspace = true }
tokio                   = { workspace = true, features = ["rt", "io-std"] }
tower-lsp               = { version = "0.20.0" }
tracing                 = { workspace = true, features = ["attributes"] }

[dev-dependencies]
pgt_test_utils = { workspace = true }
sqlx           = { workspace = true }
tokio          = { workspace = true, features = ["macros"] }
tower          = { version = "0.4.13", features = ["timeout"] }

[lib]
doctest = false
